// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuyqD8ERfCHI4KChb-9QvABBnvaBEo7gM',
    appId: '1:952736500858:web:39cacf5e066a8148edffc3',
    messagingSenderId: '952736500858',
    projectId: 'bhai-chr',
    authDomain: 'bhai-chr.firebaseapp.com',
    storageBucket: 'bhai-chr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8hJ8YVmxsA-UT_Ct8-ez9MwbThgJk6g',
    appId: '1:952736500858:android:859cd64c3dc8c0c2edffc3',
    messagingSenderId: '952736500858',
    projectId: 'bhai-chr',
    storageBucket: 'bhai-chr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVlMS-u4bmNSurGJW08jxhrdydBZ-rug4',
    appId: '1:952736500858:ios:72dfef84a527f186edffc3',
    messagingSenderId: '952736500858',
    projectId: 'bhai-chr',
    storageBucket: 'bhai-chr.appspot.com',
    iosBundleId: 'com.example.bhaiChara',
  );
}
