// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDScwC90FQy2LOYwpLipCkx0OEFFSWsQhY',
    appId: '1:161107868917:web:1374053c366edeeb2fd9bc',
    messagingSenderId: '161107868917',
    projectId: 'bhaicharag-17c95',
    authDomain: 'bhaicharag-17c95.firebaseapp.com',
    storageBucket: 'bhaicharag-17c95.firebasestorage.app',
    measurementId: 'G-P86CP76BD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD-B8uV4OsGSK7BLARdB69Hy3Mdy2RC4A',
    appId: '1:161107868917:android:cbc2ae1321ef1e482fd9bc',
    messagingSenderId: '161107868917',
    projectId: 'bhaicharag-17c95',
    storageBucket: 'bhaicharag-17c95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBICG6sqVVcaNVKppYLqvypLvLnDFWdmjc',
    appId: '1:161107868917:ios:aba310c23795aabf2fd9bc',
    messagingSenderId: '161107868917',
    projectId: 'bhaicharag-17c95',
    storageBucket: 'bhaicharag-17c95.firebasestorage.app',
    iosBundleId: 'com.example.bhaiChara',
  );

}